#version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=prod

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  node:
    image: node:14-alpine
    container_name: symfony_node
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: ["yarn", "build"]
